apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # In-cluster PostgreSQL for development
  - ../../postgres/database/in-cluster

namespace: __PROJECT_NAME__-dev

labels:
  - pairs:
      environment: development

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: oauth-proxy-config
    envs:
      - oauth-proxy.env

secretGenerator:
  - name: oauth-proxy-secret
    envs:
      - oauth-proxy-secret.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: __REGISTRY__/__PROJECT_NAME__-backend
    newTag: latest
  - name: __REGISTRY__/__PROJECT_NAME__-frontend
    newTag: latest
